# Node.js CI workflow

# base href is set in the npm build script (and then publicPath in vue.config.js)

name: Node.js CI

on: [push, pull_request, merge_group]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_PUSH_MAIN: ${{ github.ref == 'refs/heads/main' }}
      IS_PUSH_TAG: ${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'beta') }}
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run lint
      run: yarn run lint
    - name: Run tests
      run: yarn run test-ci
    - name: Build
      run: |
        BUILD_SCRIPT=build-trunk
        if ${{ env.IS_PUSH_TAG }}; then
          BUILD_SCRIPT=build-stable
        fi
        yarn run $BUILD_SCRIPT
    - name: Push to gh-pages (if tag or main branch)
      if: env.IS_PUSH_MAIN == 'true' || env.IS_PUSH_TAG == 'true'
      run: |
        DEPLOY_DIR=./demo/trunk
        if ${{ env.IS_PUSH_TAG }}; then
          DEPLOY_DIR=./demo/stable
        fi
        ALL=/*
        git config user.email github-actions@github.com
        git config user.name github-actions
        git checkout gh-pages
        rm -Rf $DEPLOY_DIR$ALL
        cp -Rf ./dist/* $DEPLOY_DIR
        git add -A $DEPLOY_DIR
        git diff-index --quiet HEAD ||
          git commit -m "CI run ${{ github.run_number }} pushed to gh-pages"
        git push -fq origin gh-pages
